routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {return view('welcome');});
Route::resource('monedas', 'CbCurrencyController');
Route::get('/welcome', function () {return view('welcome');});
Route::get('/scrap', function () {return view('scraping');});
Route::get('/register', function () {return view('auth/passwords/register');});
Route::get('/login', function () {return view('auth/passwords/login');});




//Login routes
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/CbCurrency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CbCurrency extends Model
{
    protected $table='cb_currency';
    protected $primaryKey = 'idcurrency';
    protected $fillable =  array(
						    	'currency',
						    	'description',
						    	'isactive',
						    	'isocode',
						    	'cursymbol',
						    	'precisionstd',
						    	'precisioncost',
						    	'precisionprize'
    						);
    protected $hidden = ['created_at','updated_at'];

    
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CbCurrencyController.php
<?php
 
namespace App\Http\Controllers;
 
use Illuminate\Http\Request;
 
use App\Http\Requests;
 
use App\CbCurrency;
 
class CbCurrencyController extends Controller
{
  /**
  * Muestra una lista de las monedas.
  *
  * @return Response
  */
  public function index()
  {
    // Devolverá todas las monedas
    $monedas = CbCurrency::get();
    return view('perfil.index')->with('monedas', $monedas);
  }

	  /**
	 * Muestra la moneda seleccionada por id.
	 * @param $IdCurrency 
	 * @return Response
	 */
	public function show($IdCurrency)
	{
	  // Devuelve la moneda seleccionada por id.
	  $moneda = CbCurrency::find($IdCurrency);
	  return view('perfil.show')->with('moneda', $moneda);
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('welcome');
    }
}

resources/views/app.blade.php
<html lang="en">
<head>
    <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MantMan</title>
 
  <!-- Custom CSS -->
  @section('styles_laravel')
 
  <!-- Bootstrap Core CSS -->
  <link media="all" type="text/css" rel="stylesheet" href="/assets/css/bootstrap.css">
  <link media="all" type="text/css" rel="stylesheet" href="/css/app.css">
 
  <!-- Fonts -->
  <!--link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'-->
  @show 
  @yield('mis_estilos')
</head>
<body>
    <nav class="navbar navbar-default menu">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand homebtn" href="{{url('/welcome')}}">KЯAKΣИ</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
              @if (Auth::guest())
                <li><a href="{{route('login')}}">Login</a></li>
                <li><a href="{{route('register')}}">Register</a></li>
              @else
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                                Logout
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </li>
              @endif
          </ul>
        </div>
      </div>
    </nav>
  <div class="container">
    @if (Session::has('errors'))
      <div class="alert alert-warning" role="alert">
        <ul>
          <strong>Oops! Something went wrong : </strong>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div>
    @endif
  </div>
  @yield('content')
  <!-- Scripts -->
   <!-- Scripts -->
  <script src="/assets/js/jquery.js"></script>
  <script src="/assets/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/perfil/index.blade.php
@extends('app')
@section('content')
<h1 class="text-primary">Lista de Monedas</h1>
 
<table class="table table-bordered" id="tableMonedas">
  <thead>
    <tr>
        <th class="text-center">Id moneda</th>
        <th class="text-center">Nombre</th>
        <th class="text-center">Descripción</th>
        <th class="text-center">Activa</th>
        <th class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
    @foreach($monedas as $moneda)
        <tr>
            <td class="text-center">{{ $moneda->idcurrency}}</td>
            <td class="text-center">{{ $moneda->currency}}</td>
            <td class="text-center">{{ $moneda->description }}</td>
            <td class="text-center">{{ $moneda->isactive}}</td>
            <td>
                <a href="{{ route('monedas.show', $moneda->idcurrency) }}" class="btn btn-info">Ver</a>
 
            </td>
        </tr>
    @endforeach
  </tbody>
  <tfoot>
    <tr>
      <th class="text-center">Id moneda</th>
      <th class="text-center">Nombre</th>
      <th class="text-center">Descripción</th>
      <th class="text-center">Fecha</th>
      <th class="text-center">Acciones</th>
    </tr>
  </tfoot>
</table>
@stop

resources/views/perfil/show.blade.php
@extends('app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading"><div style="text-align: center;">Hola {{ $moneda->currency}}</div></div>

                <div class="panel-body" style="background: #b7babf;border: 1px solid;">
                  <div class="col-md-6">
                  	<form action="">
					<input id="id" name="id" type="hidden" value="{{$moneda->idcurrency}}">

					<div class="layout-row min-size">
						<div class="form-tabless-fields ">
							<div class="form-group text-field is-required">
								<label for="">Name</label>
								<input
									type="text"
									name="name"
									id="name"
									value=""
									placeholder=""
									class="form-control"
									autocomplete="off"
									maxlength="255"/>
							</div>
							<div class="form-group text-field is-required">
								<label for="">Username</label>
								<input
									type="text"
									name="username"
									id="username"
									value=""
									placeholder=""
									class="form-control"
									autocomplete="off"
									maxlength="255"/>
							</div>	
							<div class="form-group text-field is-required">
								<label for="">Email</label>
								<input
									type="email"
									name="email"
									id="email"
									value=""
									placeholder=""
									class="form-control"
									autocomplete="off"
									maxlength="255"/>
							</div>
							<div class="form-group text-field">
								<label for="">Password</label>
								<input
							        type="password"
							        name="password"
							        id="password"
							        value=""
							        class="form-control"
							        autocomplete="off"
							        maxlength="255"/>
							</div>
							<div class="form-group text-field">
								<label for="">Password Confirmation</label>
								<input
							        type="password"
							        name="password_confirm"
							        id="password_confirm"
							        value=""
							        class="form-control"
							        autocomplete="off"
							        maxlength="255"/>
							</div>
							<div class="form-group text-field span-left">
								<div class="form-buttons">
						            <button
					                    type="submit"
					                    data-hotkey="ctrl+s, cmd+s"
					                    data-load-indicator="Editing User..."
					                    class="btn btn-primary form-control">
					                    Edit</button>
						        </div> 
							</div>		
						</div>	
					</div>	
				</form>
                  </div>
                  <div class="col-md-6">
                  	
                  </div>                  
                </div>                         
            </div>
        </div>
    </div>
</div>
@stop

resources/views/scraping.blade.php
@extends('app')

@section('content')
<div>
    <?php 
$html = file_get_contents('http://flirc.tv'); //Convierte la información de la URL en cadena
echo $html;
?>  
</div>
@endsection

  